Repository Anu27n/603work, pull requests merged in 2024-10, with the labels that each got.

#39 Made the navbar transparent , black color is added only when we scrolled up
  src/Navbar.js
  src/style.css
Labels: hacktoberfest, gssoc-ext, level 2, hacktoberfest-accepted

#40 Improve UI with Enhanced Styles
  package-lock.json
  src/Home.js
  src/script.js
  src/style.css
Labels: hacktoberfest, gssoc-ext, level1, hacktoberfest-accepted

#42 i have added hover effect on logo which on click rotates the logo 360…
  src/Navbar.js
  src/style.css
Labels: enhancement, good first issue, hacktoberfest, gssoc-ext, level1

#49 added text typing effect and animations
  package-lock.json
  package.json
  src/Home.js
  src/script.js
  src/style.css
Labels: CSS, gssoc-ext, level1, hacktoberfest-accepted

#53 Branch navbar updates
  src/Navbar.js
  src/style.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#63 The Spaces nav is working!
  src/Home.js
  src/Navbar.js
Labels: hacktoberfest, hacktoberfest-accepted

#69 Hamburger issue resolved
  src/Navbar.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#70 fix: remove duplicate content on landing page
  src/App.js
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create Login Signup page
  src/App.css
  src/App.js
  src/Modal.css
  src/Modal.js
  src/Navbar.js
Labels: hacktoberfest, hacktoberfest-accepted

#81 The Link of Google Map is working perfectly now
  src/Home.js
Labels: hacktoberfest, hacktoberfest-accepted

#85 added-css-features
  package-lock.json
  src/Modal.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#89 fix: bug in home.js
  src/Home.js
Labels: hacktoberfest-accepted

#92 Fix: Show hidden text, modal styling #84
  src/Modal.css
  src/Modal.js
Labels: hacktoberfest-accepted

#98 added Interactive Services page with same UI as Home page
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/Navbar.js
  src/Pages/Services/Services.css
  src/Pages/Services/Services.js
Labels: hacktoberfest-accepted

#99 making top_navbar with information more clear.
  src/style.css
Labels: hacktoberfest-accepted

#100 Added hover effect on modal buttons. Fixes #97
  src/Modal.css
Labels: hacktoberfest-accepted

#101 Added Interactive Blogs page with same UI as Home page
  src/App.js
  src/Navbar.js
  src/Pages/Blogs/BlogPost.css
  src/Pages/Blogs/BlogPost.js
  src/Pages/Blogs/Blogs.js
Labels: hacktoberfest, hacktoberfest-accepted

#107 added password strength analyzer
  package-lock.json
  package.json
  src/Modal.js
Labels: hacktoberfest-accepted

#108 Bug Fixed : Added 'Scroll to Top' button on Services and Blog pages f…
  src/Pages/Blogs/Blogs.js
  src/Pages/Services/Services.js
Labels: hacktoberfest-accepted

#110 Bug Fixed : Added missing Footer to Our Services and Blog Pages.
  src/Pages/Blogs/Blogs.js
  src/Pages/Services/Services.js
Labels: hacktoberfest-accepted

#119 feat: added contact-us page with responsive design
  src/App.js
  src/Navbar.js
  src/Pages/Contact/Contact.js
  src/Pages/Contact/Contact.module.css
  src/Pages/Contact/ContactForm.js
  src/Pages/Contact/ContactInfo.js
  src/Pages/Contact/DirectorInfo.js
  src/images/directorimage.png
Labels: hacktoberfest-accepted

#120 Feature : Implemented an interactive FAQ section on the homepage for …
  src/Home.js
  src/Pages/FAQ/FAQ.js
  src/Pages/FAQ/faq.css
  src/Pages/FAQ/faqData.json
Labels: hacktoberfest-accepted

#117 "Make Your Space" button redirects to home page instead of new page #88 SOLVED !!!
  src/Home.js
  src/Navbar.js
Labels: bug, hacktoberfest-accepted

#124 Improve Signup Card UI
  package-lock.json
  package.json
  src/Modal.css
  src/Modal.js
  src/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#125 Navbar Responsiveness issue Resolved
  src/style.css
Labels: gssoc-ext, level1, level 2, hacktoberfest-accepted

#123 Image page added.
  src/App.js
  src/Navbar.js
  src/Pages/Photos/Photos.js
Labels: hacktoberfest-accepted

#127 Fixing the navigation of to a new page book a spage button
  src/App.js
  src/Home.js
  src/Navbar.js
  src/Pages/book-a-space/book.js
  src/style.css
Labels: hacktoberfest-accepted

#129 responsive design added for top navbar
  src/style.css
Labels: hacktoberfest-accepted

#130 [STYLE:] UI changes
  src/App.css
  src/Event.css
  src/Home.js
  src/Modal.js
  src/Navbar.js
  src/Pages/Contact/Contact.module.css
  src/Pages/FAQ/FAQ.js
  src/Pages/FAQ/faq.css
  src/Pages/Photos/Photos.js
  src/Pages/Services/Services.css
  src/ScrollIndicator.js
  src/images/badge-1-bg.png
  src/images/footer-form-pattern.svg
  src/images/separator-hero.svg
  src/images/separator.svg
  src/index.css
  src/style.copy.css
  src/style.css
  src/styles/footer.css
  src/styles/global.css
  src/styles/hero.css
  src/styles/layout.css
  src/styles/media-queries.css
  src/styles/modal.css
  src/styles/navbar.css
  src/styles/reset.css
  src/styles/sections.css
  src/styles/typography.css
  src/styles/utilities.css
Labels: pro, hacktoberfest-accepted

#137 separate route files for efficient usage
  src/App.js
  src/Routes/AppRoutes.js
Labels: hacktoberfest-accepted

#138 feat: add chatbot feature with predefined Q&A
  src/App.js
  src/Components/Chatbot/Chatbot.js
  src/Components/Chatbot/chatbot.css
  src/images/bot.png
Labels: hacktoberfest-accepted

#140 Refactor: contact us page design
  src/Pages/Contact/Contact.js
  src/Pages/Contact/Contact.module.css
Labels: hacktoberfest-accepted
